```{r}
library(ggplot2)


ggplot(averages, aes(x=Genus, y=N15, fill=Type)) + geom_bar(colour = "black", stat="identity", position=position_dodge()) + geom_errorbar(aes(ymin=N15-N15_SE, ymax=N15+N15_SE), width=.2, position=position_dodge(.9), color = "grey44")+ 
scale_fill_manual(values = c("white", 'black'), labels = c('Calcified', 'Decalcified')) + 
labs(y= expression(paste(delta^{15}, 'N (‰)'), x = 'Genus'), fill = 'Samples')+ theme(axis.text.x = element_text(face = "italic")) +
scale_y_continuous(limits = c(0,4.5), expand = c(0, 0)) +
theme(axis.title = element_text(size = 15)) + 
theme(axis.text = element_text(size = 12)) + 
theme(axis.text = element_text(colour = "black")) +
theme(legend.title =  element_text(size = 15)) + 
theme(legend.text = element_text(size = 12))
ggsave("N15 ~ Decal.tiff", height = 84, width = 150, units = 'mm', dpi=1200)
```

```{r}
ggplot(averages, aes(x=Genus, y=Percent, fill=Type)) + geom_bar(colour = 'black', stat="identity", position=position_dodge()) + geom_errorbar(aes(ymin=Percent-Percent_SE, ymax=Percent+Percent_SE), width=.2, position=position_dodge(.9), color = "grey44")+ 
scale_fill_manual(values = c("white", 'black'), labels = c('Calcified', 'Decalcified')) + 
labs(y= expression(paste('% N'), x = 'Genus'), fill = 'Samples')+ theme(axis.text.x = element_text(face = "italic")) +
scale_y_continuous(limits = c(0,3), expand = c(0, 0)) +
theme(axis.title = element_text(size = 15)) + 
theme(axis.text = element_text(size = 12)) + 
theme(axis.text = element_text(colour = "black")) +
theme(legend.title =  element_text(size = 15)) + 
theme(legend.text = element_text(size = 12))
ggsave("Percent ~ Decal.tiff", height = 84, width = 150, units = 'mm',dpi=1200)
```

